rtl8723bu: concurrent_mode: fix ioctl_cfg80211.c compile errors
Error was:
ioctl_cfg80211.c: In function 'cfg80211_rtw_change_iface':
ioctl_cfg80211.c:1715:6: error: implicit declaration of function 'netdev_if2_open' [-Werror=implicit-function-declaration]
   if(netdev_if2_open(ndev) != 0) {
      ^

Fix that by adding the extern declaration. I found that in os_dep/linux/ioctl_cfg80211.c.
Seeing that version of the same file, I first wondered if it should not use
that file instead. But using that results in a long list of errors and
warnings. Therefore aboneded that and just copied the extern declaration
over instead.

Note that there are still two warnings, which I have not fixed,
and also did not not further investigated:

ioctl_cfg80211.c:5855:22: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .add_virtual_intf = cfg80211_rtw_add_virtual_intf,
                      ^
ioctl_cfg80211.c:5855:22: note: (near initialization for 'rtw_cfg80211_ops.add_virtual_intf')
ioctl_cfg80211.c:5871:18: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .dump_station = cfg80211_rtw_dump_station,
                  ^
Signed-off-by: mpvader <mvader@victronenergy.com>
Signed-off-by: Larry Finger <Larry.Finger@lwfinger.net>